baseURL = 'https://woodstea.com/'
languageCode = 'en-us'
title = "Wood's Tea"
subtitle = "In which a 59 year old data science student finds his way"

[module]
  [[module.imports]]
    path = 'github.com/adityatelange/hugo-PaperMod'
